### ISSUE TITLE
About the purpose of Webflux 

### ISSUE THREAD

**Issue by HelloTo4x** [fhfelipefh/WebfluxAndMongoDB#1]
Hi, i am reading your project, can u tell me the purpose of Webflux, reactive in your project ? Is it for increasing performance, can u tell me some disadvantaged of Webflux ?

**Comment by fhfelipefh** [comment]
#### To answer this question it is important to understand the difference between a blocking and a non-blocking flow! 

@HelloTo4x 
Assuming you have a flow where one action after another is needed, so called synchronous, you will have to wait for the completion of one to start the next and this will make the total time longer.
If your flow allows both actions to be triggered at the same time, you can decrease the total time, producing a faster response.

Spring Webflux is a module that was inserted in Spring Framework 5 and allows web applications with Spring on the server side to work in an asynchronous and non-blocking way.

Without going into details, in general, in this project of mine, actually webflux has no impact, now imagine that an application has a database called person and another called car, to save a car and a person, I need them not to exist before or to update they need to have been updated less than 1 month ago and I need to check that.
With webflux I can check both conditions at the same time and save time!

With theory and practical experience working with webflux I can make the following observations:

## advantages:

- Response speed for the user
- Allows executing parallel requests that would be too slow or unfeasible in synchronous programming
- event-driven and resilient

## disadvantages: 

- Too much learning time for developers. **(main disadvantage in my opinion)**
- The project must also use reactive database drivers and the database must be designed for webflux.
- developers must think about every decision in the functions, or they will replicate synchronous programming in webflux.
- Complex maintenance, in resume expensive.

Before applying webflux to an application, an architectural work is needed to make sure the cost is worth it, an application cannot be half synchronous and half asynchronous, if it already exists, a migration is required.

**Comment by HelloTo4x** [comment]
thank u so much
